#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
	type = 'prompt'
	alignment = 'left'

	[[blocks.segments]]
		type = 'path'
		style = 'diamond'
		foreground = 'p:black'
		background = 'p:green'
		template = ' {{ if gt (len .PWD) 7 }} {{ .PWD }} {{ else }} {{ .AbsolutePWD }} {{ end }} <p:green,transparent></>'

	[[blocks.segments]]
		type = 'git'
		style = 'diamond'
		foreground = 'p:black'
		background = 'p:blue'
		leading_diamond = '<p:black></>'
		template = ' {{ if .UpstreamURL }} {{ url .UpstreamIcon .UpstreamURL }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} <p:blue,transparent></>'

		[blocks.segments.properties]
			branch_max_length = 25
			fetch_status = true
			fetch_upstream_icon = true

[[blocks]]
	type = 'rprompt'

	[[blocks.segments]]
		type = 'status'
		style = 'diamond'
		foreground = 'p:black'
		background = 'p:blue'
		background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}', '{{ if eq .Code 0 }}p:green{{ end }}']
		leading_diamond = ''
		trailing_diamond = ''
		template = ' {{ if gt .Code 0 }} {{ .Code }}{{ else }}{{ end }} '

		[blocks.segments.properties]
			always_enabled = true

[transient_prompt]
	alignment = 'left'
	foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}', '{{ if eq .Code 0 }}p:green{{ end }}']
	background = 'transparent'
	template = ' {{ if gt (len .PWD) 7 }} {{ .PWD }} {{ else }} {{ .AbsolutePWD }} {{ end }} ⟩ '

[secondary_prompt]
	background = 'transparent'
    foreground = '#ffffff'
	template = '⟩ '

[palette]
	black = '#262B44'
	blue = '#7DB4E6'
	green = '#A8C787'
	orange = '#F07623'
	red = '#DC787B'
	white = '#C6CCD7'
	yellow = '#F3AE35'
